# Experimental Simulator of a cooperative solar system economy.
# Copyright (C) 2016  Hartmut Prochaska
# See doc/LICENSE for licensing information

# one tick is tick_lenght hours in worldtime per second realtime
# tick = 2
tick_length = 1
# needed O2 in liter per player and 6 hour tick, later value per hour
# https://www.quora.com/How-much-oxygen-does-the-average-person-burn-in-a-day-What-volume-of-air-is-that
# using the nasa values, per hour a person will need about 25l, could be higher if exercising => we will improve the model later
02_per_person = 150
# per day in kg
food_per_person = 1
# per day in kg
water_per_person = 5

[constants]
# gas equivalents http://www.airproducts.com/Products/Gases/gas-facts/conversion-formulas/weight-and-volume-equivalents/oxygen.aspx
airmix_o2 = 0.2
airmix_n2 = 0.8

[elements]
storage_method="file"
datafile="resources/PeriodicTableJSON-cleaned.json"
#source is github repository https://github.com/Bowserinator/Periodic-Table-JSON, created by Bowserinator
source="https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/master/PeriodicTableJSON.json"

[recipes]
storage_method="file"
datafile="resources/recipe.json"

[player]
storage_method ="file"
datafile="resources/player.json"

[structure]
storage_method="file"
datafile="resources/station.json"

[module]
storage_method="file"
datafile="resources/module.json"

[component]
storage_method="file"
datafile="resources/components.json"
