[package]
name = "expansion common module"
version = "0.0.1"
authors = ["freeze"]

[lib]
name = "expansion-common"
path = "src/mod.rs"

[dependencies]
piston_window = "*"
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
find_folder = "*"
