[package]
name = "expansion"
version = "0.0.1"
authors = ["Hartmut"]

[dependencies]
time = "*" # https://crates.io/crates/time
uuid = { version = "*", features = ["serde", "v4"] } # https://crates.io/crates/uuid
serde = { version = "*", features = ["derive"] } # https://crates.io/crates/serde
serde_json = "*" # https://crates.io/crates/serde_json
serde_derive = "*" # https://crates.io/crates/serde_derive
toml = "*" # https://crates.io/crates/toml
chrono = "*" # https://crates.io/crates/chrono
rand = "*" # https://doc.rust-lang.org/rand/rand/index.html
specs = "*" # https://crates.io/crates/specs
specs-hierarchy = "*" # https://github.com/rustgd/specs-hierarchy
measurements = "*" # https://crates.io/crates/measurements
amethyst = "*" # https://crates.io/crates/amethyst
amethyst_rendy = { version = "*", features = ["empty"] } # https://crates.io/crates/amethyst_rendy
amethyst_assets = "*"
amethyst_derive = "*"
amethyst_core ="*"

[features]
default = []
