[package]
name = "expansion_server"
version = "0.0.1"
authors = ["Hartmut "]

[dependencies]
time = "0.1" # https://crates.io/crates/time
uuid = { version = "*", features = ["serde", "v4"] } # https://crates.io/crates/uuid
serde = "0.8" # https://crates.io/crates/serde
serde_json = "0.8" # https://crates.io/crates/serde_json
# serde_macros = "0.8" # https://crates.io/crates/serde_macros
serde_derive = "0.8" # https://crates.io/crates/serde_derive
toml = "0.1" # https://crates.io/crates/toml

#temp, until the cargo packages got repaired for the nightly rust build
# serde_codegen = { file = "../../serde/serde_codegen"}
# serde_macros = { file = "../../serde/serde_macros"}

[features]
default = []
# secure-password = ["bcrypt"]
